### ISSUE TITLE
User/Taskデータのラッパー

### ISSUE THREAD

**Issue by Hajime12349** [Hajime12349/docker-next.js_GeekHackathon#27]

**Comment by wachinaba** [comment]
# データ型
export type Task = {
    id: number;
    user_id: string;
    task_name: string;
    deadline: string;
    total_set: number;
    current_set: number;
    is_complete: boolean;
}

export type User = {
    id?: string;
    display_name?: string;
    icon_path?: string;
    current_task?: number;
    current_task_time?: string;
}

# データ型のimport
import type { Task, User } from '@/lib/entity';

# タスクの追加
createTask(task : Task)
